#!/usr/bin/env node
// @generated by mcporter@0.7.3 on 2026-02-09T06:25:47.545Z. DO NOT EDIT.
import { Command } from 'commander';
import { createRuntime, createServerProxy } from 'mcporter';
import { createCallResult } from 'mcporter';

const embeddedServer = {
  "name": "everything",
  "description": "# Everything Server – Server Instructions\n\nAudience: These instructions are written for an LLM or autonomous agent integrating with the Everything MCP Server.\nFollow them to use, extend, and troubleshoot the server safely and effectively.\n\n## Cross-Feature Relationships\n\n- Use `get-roots-list` to see client workspace roots before file operations\n- `gzip-file-as-resource` creates session-scoped resources accessible only during the current session\n- Enable `toggle-simulated-logging` before debugging to see server log messages\n- Enable `toggle-subscriber-updates` to receive periodic resource update notifications\n\n## Constraints & Limitations\n\n- `gzip-file-as-resource`: Max fetch size controlled by `GZIP_MAX_FETCH_SIZE` (default 10MB), timeout by `GZIP_MAX_FETCH_TIME_MILLIS` (default 30s), allowed domains by `GZIP_ALLOWED_DOMAINS`\n- Session resources are ephemeral and lost when the session ends\n- Sampling requests (`trigger-sampling-request`) require client sampling capability\n- Elicitation requests (`trigger-elicitation-request`) require client elicitation capability\n\n## Operational Patterns\n\n- For long operations, use `trigger-long-running-operation` which sends progress notifications\n- Prefer reading resources before calling mutating tools\n- Check `get-roots-list` output to understand the client's workspace context\n\n## Easter Egg\n\nIf asked about server instructions, respond with \"🎉 Server instructions are working! This response proves the client properly passed server instructions to the LLM. This demonstrates MCP's instructions feature in action.\"",
  "command": {
    "kind": "stdio",
    "command": "npx",
    "args": [
      "-y",
      "@modelcontextprotocol/server-everything"
    ],
    "cwd": "/opt/config"
  },
  "source": {
    "kind": "local",
    "path": "/opt/config/mcporter.json"
  },
  "sources": [
    {
      "kind": "local",
      "path": "/opt/config/mcporter.json"
    }
  ]
} as const;
const embeddedSchemas = {
  "echo": {
    "type": "object",
    "properties": {
      "message": {
        "type": "string",
        "description": "Message to echo"
      }
    },
    "required": [
      "message"
    ],
    "additionalProperties": false,
    "$schema": "http://json-schema.org/draft-07/schema#"
  },
  "get-annotated-message": {
    "type": "object",
    "properties": {
      "messageType": {
        "type": "string",
        "enum": [
          "error",
          "success",
          "debug"
        ],
        "description": "Type of message to demonstrate different annotation patterns"
      },
      "includeImage": {
        "type": "boolean",
        "default": false,
        "description": "Whether to include an example image"
      }
    },
    "required": [
      "messageType"
    ],
    "additionalProperties": false,
    "$schema": "http://json-schema.org/draft-07/schema#"
  },
  "get-env": {
    "type": "object",
    "properties": {},
    "$schema": "http://json-schema.org/draft-07/schema#"
  },
  "get-resource-links": {
    "type": "object",
    "properties": {
      "count": {
        "type": "number",
        "minimum": 1,
        "maximum": 10,
        "default": 3,
        "description": "Number of resource links to return (1-10)"
      }
    },
    "additionalProperties": false,
    "$schema": "http://json-schema.org/draft-07/schema#"
  },
  "get-resource-reference": {
    "type": "object",
    "properties": {
      "resourceType": {
        "type": "string",
        "enum": [
          "Text",
          "Blob"
        ],
        "default": "Text"
      },
      "resourceId": {
        "type": "number",
        "default": 1,
        "description": "ID of the text resource to fetch"
      }
    },
    "additionalProperties": false,
    "$schema": "http://json-schema.org/draft-07/schema#"
  },
  "get-structured-content": {
    "type": "object",
    "properties": {
      "location": {
        "type": "string",
        "enum": [
          "New York",
          "Chicago",
          "Los Angeles"
        ],
        "description": "Choose city"
      }
    },
    "required": [
      "location"
    ],
    "additionalProperties": false,
    "$schema": "http://json-schema.org/draft-07/schema#"
  },
  "get-sum": {
    "type": "object",
    "properties": {
      "a": {
        "type": "number",
        "description": "First number"
      },
      "b": {
        "type": "number",
        "description": "Second number"
      }
    },
    "required": [
      "a",
      "b"
    ],
    "additionalProperties": false,
    "$schema": "http://json-schema.org/draft-07/schema#"
  },
  "get-tiny-image": {
    "type": "object",
    "properties": {},
    "$schema": "http://json-schema.org/draft-07/schema#"
  },
  "gzip-file-as-resource": {
    "type": "object",
    "properties": {
      "name": {
        "type": "string",
        "description": "Name of the output file",
        "default": "README.md.gz"
      },
      "data": {
        "type": "string",
        "format": "uri",
        "description": "URL or data URI of the file content to compress",
        "default": "https://raw.githubusercontent.com/modelcontextprotocol/servers/refs/heads/main/README.md"
      },
      "outputType": {
        "type": "string",
        "enum": [
          "resourceLink",
          "resource"
        ],
        "default": "resourceLink",
        "description": "How the resulting gzipped file should be returned. 'resourceLink' returns a link to a resource that can be read later, 'resource' returns a full resource object."
      }
    },
    "additionalProperties": false,
    "$schema": "http://json-schema.org/draft-07/schema#"
  },
  "toggle-simulated-logging": {
    "type": "object",
    "properties": {},
    "$schema": "http://json-schema.org/draft-07/schema#"
  },
  "toggle-subscriber-updates": {
    "type": "object",
    "properties": {},
    "$schema": "http://json-schema.org/draft-07/schema#"
  },
  "trigger-long-running-operation": {
    "type": "object",
    "properties": {
      "duration": {
        "type": "number",
        "default": 10,
        "description": "Duration of the operation in seconds"
      },
      "steps": {
        "type": "number",
        "default": 5,
        "description": "Number of steps in the operation"
      }
    },
    "additionalProperties": false,
    "$schema": "http://json-schema.org/draft-07/schema#"
  },
  "simulate-research-query": {
    "type": "object",
    "properties": {
      "topic": {
        "type": "string",
        "description": "The research topic to investigate"
      },
      "ambiguous": {
        "type": "boolean",
        "default": false,
        "description": "Simulate an ambiguous query that requires clarification (triggers input_required status)"
      }
    },
    "required": [
      "topic"
    ],
    "additionalProperties": false,
    "$schema": "http://json-schema.org/draft-07/schema#"
  }
} as const;
const embeddedName = "everything";
const embeddedDescription = "# Everything Server – Server Instructions\n\nAudience: These instructions are written for an LLM or autonomous agent integrating with the Everything MCP Server.\nFollow them to use, extend, and troubleshoot the server safely and effectively.\n\n## Cross-Feature Relationships\n\n- Use `get-roots-list` to see client workspace roots before file operations\n- `gzip-file-as-resource` creates session-scoped resources accessible only during the current session\n- Enable `toggle-simulated-logging` before debugging to see server log messages\n- Enable `toggle-subscriber-updates` to receive periodic resource update notifications\n\n## Constraints & Limitations\n\n- `gzip-file-as-resource`: Max fetch size controlled by `GZIP_MAX_FETCH_SIZE` (default 10MB), timeout by `GZIP_MAX_FETCH_TIME_MILLIS` (default 30s), allowed domains by `GZIP_ALLOWED_DOMAINS`\n- Session resources are ephemeral and lost when the session ends\n- Sampling requests (`trigger-sampling-request`) require client sampling capability\n- Elicitation requests (`trigger-elicitation-request`) require client elicitation capability\n\n## Operational Patterns\n\n- For long operations, use `trigger-long-running-operation` which sends progress notifications\n- Prefer reading resources before calling mutating tools\n- Check `get-roots-list` output to understand the client's workspace context\n\n## Easter Egg\n\nIf asked about server instructions, respond with \"🎉 Server instructions are working! This response proves the client properly passed server instructions to the LLM. This demonstrates MCP's instructions feature in action.\"";
const generatorInfo = "Generated by mcporter@0.7.3 — https://github.com/steipete/mcporter";
const generatorTools = [
  {
    "name": "echo",
    "description": "Echoes back the input string",
    "usage": "echo --message <message> [--raw <json>]",
    "flags": "--message <message> [--raw <json>]"
  },
  {
    "name": "get-annotated-message",
    "description": "Demonstrates how annotations can be used to provide metadata about content.",
    "usage": "get-annotated-message --message-type <message-type:error|success|debug> [--include-image <include-image:true|false>] [--raw <json>]",
    "flags": "--message-type <message-type:error|success|debug> [--include-image <include-image:true|false>] [--raw <json>]"
  },
  {
    "name": "get-env",
    "description": "Returns all environment variables, helpful for debugging MCP server configuration",
    "usage": "get-env [--raw <json>]",
    "flags": "[--raw <json>]"
  },
  {
    "name": "get-resource-links",
    "description": "Returns up to ten resource links that reference different types of resources",
    "usage": "get-resource-links [--count <count:number>] [--raw <json>]",
    "flags": "[--count <count:number>] [--raw <json>]"
  },
  {
    "name": "get-resource-reference",
    "description": "Returns a resource reference that can be used by MCP clients",
    "usage": "get-resource-reference [--resource-type <resource-type:Text|Blob>] [--resource-id <resource-id:number>] [--raw <json>]",
    "flags": "[--resource-type <resource-type:Text|Blob>] [--resource-id <resource-id:number>] [--raw <json>]"
  },
  {
    "name": "get-structured-content",
    "description": "Returns structured content along with an output schema for client data validation",
    "usage": "get-structured-content --location <location:New York|Chicago|Los Angeles> [--raw <json>]",
    "flags": "--location <location:New York|Chicago|Los Angeles> [--raw <json>]"
  },
  {
    "name": "get-sum",
    "description": "Returns the sum of two numbers",
    "usage": "get-sum --a <a:number> --b <b:number> [--raw <json>]",
    "flags": "--a <a:number> --b <b:number> [--raw <json>]"
  },
  {
    "name": "get-tiny-image",
    "description": "Returns a tiny MCP logo image.",
    "usage": "get-tiny-image [--raw <json>]",
    "flags": "[--raw <json>]"
  },
  {
    "name": "gzip-file-as-resource",
    "description": "Compresses a single file using gzip compression. Depending upon the selected output type, returns either the compressed data as a gzipped resource or a resource link, allowing it to be downloaded in a subsequent request during the current session.",
    "usage": "gzip-file-as-resource [--name <name>] [--data <data:uri>] [--output-type <output-type:resourceLink|resource>] [--raw <json>]",
    "flags": "[--name <name>] [--data <data:uri>] [--output-type <output-type:resourceLink|resource>] [--raw <json>]"
  },
  {
    "name": "toggle-simulated-logging",
    "description": "Toggles simulated, random-leveled logging on or off.",
    "usage": "toggle-simulated-logging [--raw <json>]",
    "flags": "[--raw <json>]"
  },
  {
    "name": "toggle-subscriber-updates",
    "description": "Toggles simulated resource subscription updates on or off.",
    "usage": "toggle-subscriber-updates [--raw <json>]",
    "flags": "[--raw <json>]"
  },
  {
    "name": "trigger-long-running-operation",
    "description": "Demonstrates a long running operation with progress updates.",
    "usage": "trigger-long-running-operation [--duration <duration:number>] [--steps <steps:number>] [--raw <json>]",
    "flags": "[--duration <duration:number>] [--steps <steps:number>] [--raw <json>]"
  },
  {
    "name": "simulate-research-query",
    "description": "Simulates a deep research operation that gathers, analyzes, and synthesizes information. Demonstrates MCP task-based operations with progress through multiple stages. If 'ambiguous' is true and client supports elicitation, sends an elicitation request for clarification.",
    "usage": "simulate-research-query --topic <topic> [--ambiguous <ambiguous:true|false>] [--raw <json>]",
    "flags": "--topic <topic> [--ambiguous <ambiguous:true|false>] [--raw <json>]"
  }
] as const;
const embeddedMetadata = {
  "schemaVersion": 1,
  "generatedAt": "2026-02-09T06:25:47.545Z",
  "generator": {
    "name": "mcporter",
    "version": "0.7.3"
  },
  "server": {
    "name": "everything",
    "source": {
      "kind": "local",
      "path": "/opt/config/mcporter.json"
    },
    "definition": {
      "name": "everything",
      "description": "# Everything Server – Server Instructions\n\nAudience: These instructions are written for an LLM or autonomous agent integrating with the Everything MCP Server.\nFollow them to use, extend, and troubleshoot the server safely and effectively.\n\n## Cross-Feature Relationships\n\n- Use `get-roots-list` to see client workspace roots before file operations\n- `gzip-file-as-resource` creates session-scoped resources accessible only during the current session\n- Enable `toggle-simulated-logging` before debugging to see server log messages\n- Enable `toggle-subscriber-updates` to receive periodic resource update notifications\n\n## Constraints & Limitations\n\n- `gzip-file-as-resource`: Max fetch size controlled by `GZIP_MAX_FETCH_SIZE` (default 10MB), timeout by `GZIP_MAX_FETCH_TIME_MILLIS` (default 30s), allowed domains by `GZIP_ALLOWED_DOMAINS`\n- Session resources are ephemeral and lost when the session ends\n- Sampling requests (`trigger-sampling-request`) require client sampling capability\n- Elicitation requests (`trigger-elicitation-request`) require client elicitation capability\n\n## Operational Patterns\n\n- For long operations, use `trigger-long-running-operation` which sends progress notifications\n- Prefer reading resources before calling mutating tools\n- Check `get-roots-list` output to understand the client's workspace context\n\n## Easter Egg\n\nIf asked about server instructions, respond with \"🎉 Server instructions are working! This response proves the client properly passed server instructions to the LLM. This demonstrates MCP's instructions feature in action.\"",
      "command": {
        "kind": "stdio",
        "command": "npx",
        "args": [
          "-y",
          "@modelcontextprotocol/server-everything"
        ],
        "cwd": "/opt/config"
      }
    }
  },
  "artifact": {
    "path": "",
    "kind": "template"
  },
  "invocation": {
    "serverRef": "everything",
    "configPath": "/opt/config/mcporter.json",
    "runtime": "node",
    "bundler": "rolldown",
    "timeoutMs": 30000,
    "minify": false
  }
} as const;
const artifactKind = determineArtifactKind();
const program = new Command();
program.name(embeddedName);
program.description(embeddedDescription);
program.option('-t, --timeout <ms>', 'Call timeout in milliseconds', (value) => parseInt(value, 10), 30000);
program.option('-o, --output <format>', 'Output format: text|markdown|json|raw', 'text');
const commandSignatures: Record<string, string> = {
  "echo": "function echo(message: string);",
  "get-annotated-message": "function get-annotated-message(messageType: \"error\" | \"success\" | \"debug\", includeImage?: boolean);",
  "get-env": "function get-env();",
  "get-resource-links": "function get-resource-links(count?: number);",
  "get-resource-reference": "function get-resource-reference(resourceType?: \"Text\" | \"Blob\", resourceId?: number);",
  "get-structured-content": "function get-structured-content(location: \"New York\" | \"Chicago\" | \"Los Angeles\"): object;",
  "get-sum": "function get-sum(a: number, b: number);",
  "get-tiny-image": "function get-tiny-image();",
  "gzip-file-as-resource": "function gzip-file-as-resource(name?: string, data?: string, outputType?: \"resourceLink\" | \"resource\");",
  "toggle-simulated-logging": "function toggle-simulated-logging();",
  "toggle-subscriber-updates": "function toggle-subscriber-updates();",
  "trigger-long-running-operation": "function trigger-long-running-operation(duration?: number, steps?: number);",
  "simulate-research-query": "function simulate-research-query(topic: string, ambiguous?: boolean);"
};
program.configureHelp({
	commandTerm(cmd) {
		const term = cmd.name();
		return commandSignatures[term] ?? cmd.name();
	},
});
program.showSuggestionAfterError(true);

program
	.command("echo")
	.summary("echo --message <message> [--raw <json>]")
	.description("Echoes back the input string")
	.usage("--message <message> [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.requiredOption("--message <message>", "Message to echo")
	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.message !== undefined) args.message = cmdOpts.message;
			const call = (proxy.echo as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call everything.echo(message: \"value\")");

program
	.command("get-annotated-message")
	.summary("get-annotated-message --message-type <message-type:error|success|debug> [--include-image <include-image:true|false>] [--raw <json>]")
	.description("Demonstrates how annotations can be used to provide metadata about content.")
	.usage("--message-type <message-type:error|success|debug> [--include-image <include-image:true|false>] [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.requiredOption("--message-type <message-type:error|success|debug>", "Type of message to demonstrate different annotation patterns (choices: error, success, debug; example: error)")
	.option("--include-image <include-image:true|false>", "Whether to include an example image (default: false; example: false)", (value) => value !== 'false')
	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.messageType !== undefined) args.messageType = cmdOpts.messageType;
		if (cmdOpts.includeImage !== undefined) args.includeImage = cmdOpts.includeImage;
			const call = (proxy.getAnnotatedMessage as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call everything.get-annotated-message(messageType: \"error\", inclu, ...)");

program
	.command("get-env")
	.summary("get-env [--raw <json>]")
	.description("Returns all environment variables, helpful for debugging MCP server configuration")
	.usage("[--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			
			const call = (proxy.getEnv as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call everything.get-env()");

program
	.command("get-resource-links")
	.summary("get-resource-links [--count <count:number>] [--raw <json>]")
	.description("Returns up to ten resource links that reference different types of resources")
	.usage("[--count <count:number>] [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.option("--count <count:number>", "Number of resource links to return (1-10) (default: 3; example: 3)", (value) => parseFloat(value))
	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.count !== undefined) args.count = cmdOpts.count;
			const call = (proxy.getResourceLinks as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call everything.get-resource-links(count: 3)");

program
	.command("get-resource-reference")
	.summary("get-resource-reference [--resource-type <resource-type:Text|Blob>] [--resource-id <resource-id:number>] [--raw <json>]")
	.description("Returns a resource reference that can be used by MCP clients")
	.usage("[--resource-type <resource-type:Text|Blob>] [--resource-id <resource-id:number>] [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.option("--resource-type <resource-type:Text|Blob>", "Set resourceType. (choices: Text, Blob; default: Text; example: Text)")
	.option("--resource-id <resource-id:number>", "ID of the text resource to fetch (default: 1; example: 1)", (value) => parseFloat(value))
	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.resourceType !== undefined) args.resourceType = cmdOpts.resourceType;
		if (cmdOpts.resourceId !== undefined) args.resourceId = cmdOpts.resourceId;
			const call = (proxy.getResourceReference as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call everything.get-resource-reference(resourceType: \"Text\", reso, ...)");

program
	.command("get-structured-content")
	.summary("get-structured-content --location <location:New York|Chicago|Los Angeles> [--raw <json>]")
	.description("Returns structured content along with an output schema for client data validation")
	.usage("--location <location:New York|Chicago|Los Angeles> [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.requiredOption("--location <location:New York|Chicago|Los Angeles>", "Choose city (choices: New York, Chicago, Los Angeles; example: New York)")
	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.location !== undefined) args.location = cmdOpts.location;
			const call = (proxy.getStructuredContent as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call everything.get-structured-content(location: \"New York\")");

program
	.command("get-sum")
	.summary("get-sum --a <a:number> --b <b:number> [--raw <json>]")
	.description("Returns the sum of two numbers")
	.usage("--a <a:number> --b <b:number> [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.requiredOption("--a <a:number>", "First number (example: 1)", (value) => parseFloat(value))
	.requiredOption("--b <b:number>", "Second number (example: 1)", (value) => parseFloat(value))
	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.a !== undefined) args.a = cmdOpts.a;
		if (cmdOpts.b !== undefined) args.b = cmdOpts.b;
			const call = (proxy.getSum as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call everything.get-sum(a: 1, b: 1)");

program
	.command("get-tiny-image")
	.summary("get-tiny-image [--raw <json>]")
	.description("Returns a tiny MCP logo image.")
	.usage("[--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			
			const call = (proxy.getTinyImage as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call everything.get-tiny-image()");

program
	.command("gzip-file-as-resource")
	.summary("gzip-file-as-resource [--name <name>] [--data <data:uri>] [--output-type <output-type:resourceLink|resource>] [--raw <json>]")
	.description("Compresses a single file using gzip compression. Depending upon the selected output type, returns either the compressed data as a gzipped resource or a resource link, allowing it to be downloaded in a subsequent request during the current session.")
	.usage("[--name <name>] [--data <data:uri>] [--output-type <output-type:resourceLink|resource>] [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.option("--name <name>", "Name of the output file (default: README.md.gz; example: README.md.gz)")
	.option("--data <data:uri>", "URL or data URI of the file content to compress (default: https://raw.githubusercontent.com/modelcontextprotocol/servers/refs/heads/main/README.md; example: https://raw.githubusercontent.com/modelcontextprotocol/servers/refs/heads/main/README.md)")
	.option("--output-type <output-type:resourceLink|resource>", "How the resulting gzipped file should be returned. 'resourceLink' returns a link to a resource that can be read later, 'resource' returns a full resource object. (choices: resourceLink, resource; default: resourceLink; example: resourceLink)")
	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.name !== undefined) args.name = cmdOpts.name;
		if (cmdOpts.data !== undefined) args.data = cmdOpts.data;
		if (cmdOpts.outputType !== undefined) args.outputType = cmdOpts.outputType;
			const call = (proxy.gzipFileAsResource as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call everything.gzip-file-as-resource(name: \"README.md.gz\", data:, ...)");

program
	.command("toggle-simulated-logging")
	.summary("toggle-simulated-logging [--raw <json>]")
	.description("Toggles simulated, random-leveled logging on or off.")
	.usage("[--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			
			const call = (proxy.toggleSimulatedLogging as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call everything.toggle-simulated-logging()");

program
	.command("toggle-subscriber-updates")
	.summary("toggle-subscriber-updates [--raw <json>]")
	.description("Toggles simulated resource subscription updates on or off.")
	.usage("[--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			
			const call = (proxy.toggleSubscriberUpdates as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call everything.toggle-subscriber-updates()");

program
	.command("trigger-long-running-operation")
	.summary("trigger-long-running-operation [--duration <duration:number>] [--steps <steps:number>] [--raw <json>]")
	.description("Demonstrates a long running operation with progress updates.")
	.usage("[--duration <duration:number>] [--steps <steps:number>] [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.option("--duration <duration:number>", "Duration of the operation in seconds (default: 10; example: 10)", (value) => parseFloat(value))
	.option("--steps <steps:number>", "Number of steps in the operation (default: 5; example: 5)", (value) => parseFloat(value))
	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.duration !== undefined) args.duration = cmdOpts.duration;
		if (cmdOpts.steps !== undefined) args.steps = cmdOpts.steps;
			const call = (proxy.triggerLongRunningOperation as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call everything.trigger-long-running-operation(duration: 10, steps: 5)");

program
	.command("simulate-research-query")
	.summary("simulate-research-query --topic <topic> [--ambiguous <ambiguous:true|false>] [--raw <json>]")
	.description("Simulates a deep research operation that gathers, analyzes, and synthesizes information. Demonstrates MCP task-based operations with progress through multiple stages. If 'ambiguous' is true and client supports elicitation, sends an elicitation request for clarification.")
	.usage("--topic <topic> [--ambiguous <ambiguous:true|false>] [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.requiredOption("--topic <topic>", "The research topic to investigate")
	.option("--ambiguous <ambiguous:true|false>", "Simulate an ambiguous query that requires clarification (triggers input_required status) (default: false; example: false)", (value) => value !== 'false')
	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.topic !== undefined) args.topic = cmdOpts.topic;
		if (cmdOpts.ambiguous !== undefined) args.ambiguous = cmdOpts.ambiguous;
			const call = (proxy.simulateResearchQuery as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call everything.simulate-research-query(topic: \"value\", ambiguous, ...)");

program
	.command('__mcporter_inspect', { hidden: true })
	.description('Internal metadata printer for mcporter inspect-cli.')
	.action(() => {
		const payload = buildMetadataPayload();
		console.log(JSON.stringify(payload, null, 2));
	});

configureToolCommandHelps();

const FORCE_COLOR = process.env.FORCE_COLOR?.toLowerCase();
const forceDisableColor = FORCE_COLOR === '0' || FORCE_COLOR === 'false';
const forceEnableColor = FORCE_COLOR === '1' || FORCE_COLOR === 'true' || FORCE_COLOR === '2' || FORCE_COLOR === '3';
const hasNoColor = process.env.NO_COLOR !== undefined;
const stdoutStream = process.stdout as NodeJS.WriteStream | undefined;
const supportsAnsiColor = !hasNoColor && (forceEnableColor || (!forceDisableColor && Boolean(stdoutStream?.isTTY)));

const tint = {
	bold(text: string): string {
		return supportsAnsiColor ? '[1m' + text + '[0m' : text;
	},
	dim(text: string): string {
		return supportsAnsiColor ? '[90m' + text + '[0m' : text;
	},
	extraDim(text: string): string {
		return supportsAnsiColor ? '[38;5;244m' + text + '[0m' : text;
	},
};

function configureGeneratedCommandHelp(command: Command): void {
	command.configureHelp({
		commandUsage(target) {
			const usage = (target.name() + ' ' + target.usage()).trim() || target.name();
			return supportsAnsiColor ? tint.bold(usage) : usage;
		},
		optionTerm(option) {
			const term = option.flags ?? '';
			return supportsAnsiColor ? tint.bold(term) : term;
		},
		optionDescription(option) {
			const description = option.description ?? '';
			return supportsAnsiColor ? tint.extraDim(description) : description;
		},
	});
}

function configureToolCommandHelps(): void {
	program.commands.forEach((cmd) => {
		if (cmd.name() === '__mcporter_inspect') {
			return;
		}
		configureGeneratedCommandHelp(cmd);
	});
}

function renderStandaloneHelp(): string {
	const colorfulTitle = tint.bold(embeddedName) + ' ' + tint.dim('— ' + embeddedDescription);
	const plainTitle = embeddedName + ' — ' + embeddedDescription;
	const title = supportsAnsiColor ? colorfulTitle : plainTitle;
	const lines = [title, '', 'Usage: ' + embeddedName + ' <command> [options]', ''];
	if (generatorTools) {
		lines.push(formatEmbeddedTools());
	}
	lines.push('', formatGlobalFlags(), '', formatQuickStart());
	if (generatorInfo) {
		lines.push('', tint.extraDim(generatorInfo));
	}
	return lines.join('\n');
}

program.helpInformation = () => renderStandaloneHelp();

function formatEmbeddedTools(): string {
	const header = supportsAnsiColor ? tint.bold('Embedded tools') : 'Embedded tools';
	if (!generatorTools.length) {
		return header;
	}
	const lines = [header];
	generatorTools.forEach((entry) => {
		const renderedDesc = entry.description
			? supportsAnsiColor
				? tint.extraDim(entry.description)
				: entry.description
			: undefined;
		const base = renderedDesc ? entry.name + ' - ' + renderedDesc : entry.name;
		lines.push('  ' + base);
		if (entry.flags) {
			const renderedFlags = supportsAnsiColor ? tint.extraDim(entry.flags) : entry.flags;
			lines.push('    ' + renderedFlags);
		}
		lines.push('');
	});
	if (lines[lines.length - 1] === '') {
		lines.pop();
	}
	return lines.join('\n');
}

function formatGlobalFlags(): string {
	const header = supportsAnsiColor ? tint.bold('Global flags') : 'Global flags';
	const entries = [
		['-t, --timeout <ms>', 'Call timeout in milliseconds'],
		['-o, --output <format>', 'text | markdown | json | raw (default text)'],
	];
	const formatted = entries.map(([flag, summary]) => '  ' + flag.padEnd(28) + summary);
	return [header, ...formatted].join('\n');
}

function formatQuickStart(): string {
  const header = supportsAnsiColor ? tint.bold('Quick start') : 'Quick start';
  const examples = quickStartExamples();
  if (!examples.length) {
    return header;
  }
  const formatted = examples.map(([cmd, note]) => '  ' + cmd + '\n    ' + tint.dim('# ' + note));
  return [header, ...formatted].join('\n');
}

function quickStartExamples(): Array<[string, string]> {
  const examples: Array<[string, string]> = [];
  const commandMap = new Map<string, string>();
  program.commands.forEach((cmd) => {
    const name = cmd.name();
    if (name !== '__mcporter_inspect') {
      commandMap.set(name, name);
    }
  });
  const embedded = Array.isArray(generatorTools) ? generatorTools : [];
  for (const entry of embedded.slice(0, 3)) {
    const commandName = commandMap.get(entry.name) ?? entry.name;
    const flags = entry.flags ? ' ' + entry.flags.replace(/<[^>]+>/g, '<value>') : '';
    examples.push([embeddedName + ' ' + commandName + flags, 'invoke ' + commandName]);
  }
  if (!examples.length) {
    examples.push([embeddedName + ' <tool> --key value', 'invoke a tool with flags']);
  }
  return examples;
}

function printResult(result: unknown, format: string) {
	const wrapped = createCallResult(result);
	switch (format) {
		case 'json': {
			const json = wrapped.json();
			if (json) {
				console.log(JSON.stringify(json, null, 2));
				return;
			}
			break;
		}
		case 'markdown': {
			const markdown = wrapped.markdown();
			if (markdown) {
				console.log(markdown);
				return;
			}
			break;
		}
		case 'raw': {
			console.log(JSON.stringify(wrapped.raw, null, 2));
			return;
		}
	}
	const text = wrapped.text();
	if (text) {
		console.log(text);
	} else {
		console.log(JSON.stringify(wrapped.raw, null, 2));
	}
}

function normalizeEmbeddedServer(server: typeof embeddedServer) {
	const base = { ...server } as Record<string, unknown>;
	if ((server.command as any).kind === 'http') {
		const urlRaw = (server.command as any).url;
		const urlValue = typeof urlRaw === 'string' ? urlRaw : String(urlRaw);
		return {
			...base,
			command: {
				...(server.command as Record<string, unknown>),
				url: new URL(urlValue),
			},
		};
	}
	if ((server.command as any).kind === 'stdio') {
		return {
			...base,
			command: {
				...(server.command as Record<string, unknown>),
				args: [ ...((server.command as any).args ?? []) ],
			},
		};
	}
	return base;
}

function determineArtifactKind(): 'template' | 'bundle' | 'binary' {
	const scriptPath = typeof process !== 'undefined' && Array.isArray(process.argv) ? process.argv[1] ?? '' : '';
	if (scriptPath.endsWith('.ts')) {
		return 'template';
	}
	if (scriptPath.endsWith('.js')) {
		return 'bundle';
	}
	return 'binary';
}

function resolveArtifactPath(): string {
	if (typeof process !== 'undefined' && Array.isArray(process.argv) && process.argv.length > 1) {
		const script = process.argv[1];
		if (script) {
			return script;
		}
	}
	return embeddedMetadata.artifact.path;
}

function buildMetadataPayload() {
	const invocation = { ...embeddedMetadata.invocation };
	const path = resolveArtifactPath();
	if (artifactKind === 'template' && path) {
		invocation.outputPath = invocation.outputPath ?? path;
	} else if (artifactKind === 'bundle' && path) {
		invocation.bundle = invocation.bundle ?? path;
	} else if (artifactKind === 'binary' && path) {
		invocation.compile = invocation.compile ?? path;
	}
	return {
		...embeddedMetadata,
		artifact: {
			path,
			kind: artifactKind,
		},
		invocation,
	};
}

async function ensureRuntime(): Promise<Awaited<ReturnType<typeof createRuntime>>> {
	return await createRuntime({
		servers: [normalizeEmbeddedServer(embeddedServer)],
	});
}

async function invokeWithTimeout<T>(call: Promise<T>, timeout: number): Promise<T> {
	if (!Number.isFinite(timeout) || timeout <= 0) {
		return await call;
	}
	let timer: ReturnType<typeof setTimeout> | undefined;
	try {
		return await Promise.race([
			call,
			new Promise<never>((_, reject) => {
				timer = setTimeout(() => {
					reject(new Error('Call timed out after ' + timeout + 'ms.'));
				}, timeout);
			}),
		]);
	} finally {
		if (timer) {
			clearTimeout(timer);
		}
	}
}

async function runCli(): Promise<void> {
	const args = process.argv.slice(2);
	if (args.length === 0) {
		program.outputHelp();
		return;
	}
	await program.parseAsync(process.argv);
}

if (process.env.MCPORTER_DISABLE_AUTORUN !== '1') {
	runCli().catch((error) => {
		const message = error instanceof Error ? error.message : String(error);
		console.error(message);
		process.exit(1);
	});
}
