name: Deploy to GitHub Pages

on:
  push:
    branches:
      - github-vue

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install and Build
        working-directory: workspace/vue/geminon-lcars
        run: |
          npm install
          npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GH_PAGES_TOKEN }}
          folder: workspace/vue/geminon-lcars/dist
          branch: gh-pages
