# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-02-11T22:52:24+00:00

from __future__ import annotations

from pydantic import AwareDatetime, BaseModel


class TicketInput(BaseModel):
    title: str | None = None
    description: str | None = None
    status: str | None = 'Open'
    area_of_concern: str | None = None
    agent_name: str | None = None
    resolution_message: str | None = None


class Ticket(TicketInput):
    id: int | None = None
    created_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None
